name: mydotnetProject

on:
  push:
    branches:
      - develop  # Runs only when you push to the 'develop' branch

jobs:
  dotnet_publish:
    runs-on: self-hosted  # Make sure your runner has this label

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Publish .NET project
        run: dotnet publish src/Presentation/Nop.Web/Nop.Web.csproj -c Release -o demo
