name: Build and Push to ECR

on:
  push:
    branches:
      - develop   # Trigger when you push to develop branch

jobs:
  build:
    runs-on: self-hosted

    steps:
    # 1️⃣ Checkout source code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: eu-north-1   # 👈 change to your AWS region

    # 3️⃣ Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 4️⃣ Build and Push Docker Image
    - name: Build, tag, and push image to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ecr_dotnet_repo    # 👈 your ECR repo name
        IMAGE_TAG: latest
      run: |
        echo "Building Docker image..."
        docker build -f dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG 699475951176.dkr.ecr.eu-north-1.amazonaws.com/ecr_dotnet_repo:latest
        echo "Pushing image to ECR..."
        docker push 699475951176.dkr.ecr.eu-north-1.amazonaws.com/ecr_dotnet_repo:latest
        echo "Pushing image to ECR..."

    # 5️⃣ (Optional) Show image URL
    - name: Display Image URL
      run: echo "✅ Image pushed to: ${{ steps.login-ecr.outputs.registry }}/ecr_dotnet_repo:latest"
