name: Scan ECR Image with Trivy (Table Report)

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  scan:
    runs-on: self-hosted
    env:
      aws_region: eu-north-1
      ECR_REPOSITORY: ecr_dotnet_repo
      IMAGE_TAG: latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Run Trivy vulnerability scan (table output)
        run: |
          echo "Scanning ECR image for vulnerabilities..."
          docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

          echo ""
          echo "==================== TRIVY SCAN START ===================="
          trivy image \
            --exit-code 0 \
            --format table \
            --output trivy-report.txt \
            --ignore-unfixed \
            --pkg-types os,library \
            --severity CRITICAL,HIGH \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

          echo "==================== TRIVY SCAN END ======================"
          echo ""
          echo "✅ Trivy scan completed. Report saved as trivy-report.txt"
          echo "----------------------------------------------------------"
          cat trivy-report.txt

      - name: Upload Trivy text report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-text-report
          path: trivy-report.txt
